// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdcqozqhcmrvwzhkprwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkY3FvenFoY21ydnd6aGtwcnd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTA0ODQsImV4cCI6MjA1OTE2NjQ4NH0.laSjSXmnajsjOn0wdSSjhsxtlib7pu01a03OR4VA5ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);